permalink: /:year/:month/:day/:title.html
markdown: kramdown
pygments: true

kramdown:
  input: GFM

# 作者信息
author: 
  name: 朱同华
  email: tonghuazhu@gmail.com
  link: http://zhutonghua.cn
  weibo: http://www.weibo.com/u/1847093092
  github: http://github.com/z00216423

# 站点信息
title: 不再停留 
description: 朱同华的个人主页
url: http://zhutonghua.cn
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: https://avatars0.githubusercontent.com/u/8267109?v=3&s=400
favicon: https://avatars2.githubusercontent.com/u/8267109?v=3&s=40

# google analytics 设置
#ga:
#  id: 
#  url: zhutonghua.cn

# disqus 设置
disqus:
  shortname: Frank